apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeshop
spec:
  selector:
    matchLabels:
      app: coffee
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffeeshop
        image: yathish123/newweb
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-appservice
spec:
  type: NodePort
  selector:
    app: coffee
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
