apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeshop
spec:
  selector:
    matchLabels:
      app: coffee
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffeeshop
        image: yathish123/newweb
        ports:
        - containerPort: 80
